var config = {
    app: {
        maxusers: 150,
        countries: [],
        regions: [
          {region: "Germany", market: "MBD", country: "Germany", code: "de"},
          {region: "Greater China", market: "BMBS", country: "China", code: "cn"},
          {region: "Greater China", market: "MBTw", country: "Taiwan", code: "tw"},
          {region: "Nafta", market: "MBUSA", country: "USA", code: "us"},
          {region: "Nafta", market: "MBC", country: "Canada", code: "ca"},
          {region: "Nafta", market: "MBMex", country: "Mexico", code: "mx"},
          {region: "Europe", market: "MBUK", country: "United Kingdom", code: "gb"},
          {region: "Europe", market: "MBBel", country: "Belgium", code: "be"},
          {region: "Europe", market: "MBE", country: "Spain", code: "es"},
          {region: "Europe", market: "MBF", country: "France", code: "fr"},
          {region: "Europe", market: "MBI", country: "Italy", code: "it"},
          {region: "Europe", market: "MBLux", country: "Luxembourg", code: "lu"},
          {region: "Europe", market: "MBNL", country: "Netherlands", code: "nl"},
          {region: "Europe", market: "MBCZ", country: "Czech Republic", code: "cz"},
          {region: "Europe", market: "MBPol", country: "Poland", code: "pl"},
          {region: "Europe", market: "MBDan", country: "Denmark", code: "dk"},
          {region: "Europe", market: "MBSve", country: "Sweden", code: "se"},
          {region: "Europe", market: "MBCH", country: "Switzerland", code: "ch"},
          {region: "Europe", market: "MBP", country: "Portugal", code: "pt"},
          {region: "Europe", market: "MBH", country: "Greece", code: "gr"},
          {region: "Europe", market: "MBÖ", country: "Austria", code: "at"},
          {region: "Europe", market: "GD", country: "Finland", code: "fi"},
          {region: "Europe", market: "GD", country: "Norway", code: "no"},
          {region: "Europe", market: "GD", country: "Ireland", code: "ie"},
          {region: "Overseas", market: "MBJ", country: "Japan", code: "jp"},
          {region: "Overseas", market: "MBR", country: "Russia", code: "ru"},
          {region: "Overseas", market: "MBSA", country: "South Africa", code: "za"},
          {region: "Overseas", market: "MBKL", country: "Korea", code: "kr"},
          {region: "Overseas", market: "MBT", country: "Turkey", code: "tr"},
          {region: "Overseas", market: "MBAuP", country: "Australia Pacific", code: "au"},
          {region: "Overseas", market: "MBNZ", country: "New Zealand", code: "nz"},
          {region: "Overseas", market: "MBArg.", country: "Argentina", code: "ar"},
          {region: "Overseas", market: "MBBras", country: "Brasil", code: "br"},
          {region: "Overseas", market: "MBIL", country: "India", code: "in"},
          {region: "Overseas", market: "Central Europe/Eastern Europe", country: "Hungary", code: "hu"},
          {region: "Overseas", market: "Central Europe/Eastern Europe", country: "Slovakia", code: "sk"},
          {region: "Overseas", market: "Central Europe/Eastern Europe", country: "Romania", code: "ro"},
          {region: "Overseas", market: "Central Europe/Eastern Europe", country: "Bulgaria", code: "bg"},
          {region: "Overseas", market: "Central Europe/Eastern Europe", country: "Croatia", code: "hr"},
          {region: "Overseas", market: "Central Europe/Eastern Europe", country: "Estonia", code: "ee"},
          {region: "Overseas", market: "Central Europe/Eastern Europe", country: "Lithuania", code: "lt"},
          {region: "Overseas", market: "Central Europe/Eastern Europe", country: "Serbia", code: "rs"},
          {region: "Overseas", market: "Central Europe/Eastern Europe", country: "Ukraine", code: "ua"},
          {region: "Overseas", market: "Central Europe/Eastern Europe", country: "Latvia", code: "lv"},
          {region: "Overseas", market: "Central Europe/Eastern Europe", country: "Israel", code: "il"},
          {region: "Overseas", market: "Central Europe/Eastern Europe", country: "Slovenia", code: "si"},
          {region: "Overseas", market: "Africa", country: "Egypt", code: "eg"},
          {region: "Overseas", market: "Africa", country: "Morocco", code: "ma"},
          {region: "Overseas", market: "South East Asia", country: "Malaysia", code: "my"},
          {region: "Overseas", market: "South East Asia", country: "Thailand", code: "th"},
          {region: "Overseas", market: "South East Asia", country: "Vietnam", code: "vn"},
          {region: "Overseas", market: "South East Asia", country: "Singapore", code: "sg"},
          {region: "Overseas", market: "South East Asia", country: "Indonesia", code: "id"},
          {region: "Overseas", market: "Daimler Middle East and Levant", country: "Saudi Arabia", code: "sa"},
          {region: "Overseas", market: "Daimler Middle East and Levant", country: "United Arab Emirates", code: "ae"},
          {region: "Overseas", market: "Daimler Middle East and Levant", country: "Qatar", code: "qa"},
          {region: "Overseas", market: "Daimler Middle East and Levant", country: "Kuwait", code: "kw"},
          {region: "Overseas", market: "Daimler Middle East and Levant", country: "Oman", code: "om"},
          {region: "Overseas", market: "Daimler Middle East and Levant", country: "Jordan", code: "jo"},
          {region: "Overseas", market: "Daimler Middle East and Levant", country: "Bahrain", code: "bh"}
        ]
    },
    server: {
        host: '127.0.0.1',
        port: 81
    },
    mongo: {
        host: '127.0.0.1',
        db: 'catt-prod',
        url: 'mongodb://127.0.0.1/catt-prod',
        user:'AdminApp',
        password:'CFT^vgy7'
    },
    admin: {
        email: 'super@accenture.com',
        password: 'Pa55word',
        name: 'Super Admin',
        blocktimeout: 30, // minutes to block users after 'failedloginsbeforeblock' (see bellow) failed loggings
        failedloginsbeforeblock: 7
    },
    s3: {
        AWS_ACCESS_KEY: 'AKIAJOCZOVNLXBRTNRLQ',
        AWS_SECRET_KEY: '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',
        BUCKET: 'catt-file',
        REGION: 'eu-central-1'
    },

    SES: {
        AWS_ACCESS_KEY: 'AKIAJOCZOVNLXBRTNRLQ',
        AWS_SECRET_KEY: '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',
        REGION: 'eu-west-1',
        SMTP_Username:'AKIAIHYDE5HJGXLEJXHQ',
        SMTP_Password: 'AsKAYK9cpDfd5xsiYEqIpI61E8ttYkLYFB7O565IDg5Y',
        IAM_user:'ses-smtp-user.20170306-134204',
        rateLimit: 5 //IAM user for SMTP authentication with Amazon SES 
       /* The new user will be granted the following IAM policy:
        "Statement": [{  "Effect":"Allow",  "Action":"ses:SendRawEmail",  "Resource":"*"}]*/
        }
};


// Here for future use. Some countries are included twice with alternative names.
var countries = {
    "Afghanistan": "af",
    "Aland Islands": "ax",
    "Albania": "al",
    "Algeria": "dz",
    "American Samoa": "as",
    "Andorra": "ad",
    "Angola": "ao",
    "Anguilla": "ai",
    "Antarctica": "aq",
    "Antigua and Barbuda": "ag",
    "Argentina": "ar",
    "Armenia": "am",
    "Aruba": "aw",
    "Australia": "au",
    "Austria": "at",
    "Australia Pacific": "au",
    "Azerbaijan": "az",
    "Bahamas": "bs",
    "Bahrain": "bh",
    "Bangladesh": "bd",
    "Barbados": "bb",
    "Belarus": "by",
    "Belgium": "be",
    "Belize": "bz",
    "Benin": "bj",
    "Bermuda": "bm",
    "Bhutan": "bt",
    "Bolivia": "bo",
    "Bosnia and Herzegovina": "ba",
    "Botswana": "bw",
    "Bouvet Island": "bv",
    "Brasil": "br",
    "British Virgin Islands": "vg",
    "British Indian Ocean Territory": "io",
    "Brunei Darussalam": "bn",
    "Bulgaria": "bg",
    "Burkina Faso": "bf",
    "Burundi": "bi",
    "Cambodia": "kh",
    "Cameroon": "cm",
    "Canada": "ca",
    "Cape Verde": "cv",
    "Cayman Islands": "ky",
    "Central African Republic": "cf",
    "Chad": "td",

    "Chile": "cl",
    "China": "cn",
    "Hong Kong": "hk",

    "Macao": "mo",
    "Christmas Island": "cx",
    "Cocos (Keeling) Islands": "cc",
    "Colombia": "co",
    "Comoros": "km",
    "Congo": "cg",
    "Congo": "cd",
    "Cook Islands": "ck",
    "Costa Rica": "cr",
    "Côte d'Ivoire": "ci",
    "Croatia": "hr",
    "Cuba": "cu",
    "Cyprus": "cy",
    "Czech Republic": "cz",
    "Denmark": "dk",
    "Djibouti": "dj",
    "Dominica": "dm",
    "Dominican Republic": "do",
    "Ecuador": "ec",
    "Egypt": "eg",
    "El Salvador": "sv",
    "Equatorial Guinea": "gq",
    "Eritrea": "er",
    "Estonia": "ee",
    "Ethiopia": "et",

    "Falkland Islands (Malvinas)": "fk",
    "Faroe Islands": "fo",

    "Fiji": "fj",
    "Finland": "fi",
    "France": "fr",
    "French Guiana": "gf",
    "French Polynesia": "pf",
    "French Southern Territories": "tf",
    "Gabon": "ga",
    "Gambia": "gm",
    "Georgia": "ge",
    "Germany": "de",
    "Ghana": "gh",
    "Gibraltar": "gi",
    "Greece": "gr",
    "Greenland": "gl",
    "Grenada": "gd",
    "Guadeloupe": "gp",
    "Guam": "gu",
    "Guatemala": "gt",
    "Guernsey": "gg",
    "Guinea": "gn",
    "Guinea-Bissau": "gw",
    "Guyana": "gy",
    "Haiti": "ht",
    "Heard Island and Mcdonald Islands": "hm",
    "Holy See": "va",
    "Honduras": "hn",
    "Hungary": "hu",
    "Iceland": "is",
    "India": "in",
    "Indonesia": "id",
    "Iran, Islamic Republic of": "ir",
    "Iraq": "iq",
    "Ireland": "ie",
    "Isle of Man": "im",
    "Israel": "il",
    "Italy": "it",
    "Jamaica": "jm",
    "Japan": "jp",
    "Jersey": "je",
    "Jordan": "jo",
    "Kazakhstan": "kz",
    "Kenya": "ke",
    "Kiribati": "ki",
    "Korea, Democratic People's Republic of": "kp",
    "Korea, Republic of": "kr",
    "Korea": "kr", // South Korea
    "Kuwait": "kw",
    "Kyrgyzstan": "kg",
    "Lao PDR": "la",
    "Latvia": "lv",
    "Lebanon": "lb",
    "Lesotho": "ls",
    "Liberia": "lr",
    "Libya": "ly",
    "Liechtenstein": "li",
    "Lithuania": "lt",
    "Luxembourg": "lu",
    "Macedonia, Republic of": "mk",
    "Madagascar": "mg",
    "Malawi": "mw",
    "Malaysia": "my",
    "Maldives": "mv",
    "Mali": "ml",
    "Malta": "mt",
    "Marshall Islands": "mh",
    "Martinique": "mq",
    "Mauritania": "mr",
    "Mauritius": "mu",
    "Mayotte": "yt",
    "Mexico": "mx",
    "Micronesia, Federated States of": "fm",
    "Moldova": "md",
    "Monaco": "mc",
    "Mongolia": "mn",
    "Montenegro": "me",
    "Montserrat": "ms",
    "Morocco": "ma",
    "Mozambique": "mz",
    "Myanmar": "mm",
    "Namibia": "na",
    "Nauru": "nr",
    "Nepal": "np",
    "Netherlands": "nl",
    "Netherlands Antilles": "an",
    "New Caledonia": "nc",
    "New Zealand": "nz",
    "Nicaragua": "ni",
    "Niger": "ne",
    "Nigeria": "ng",
    "Niue": "nu",
    "Norfolk Island": "nf",
    "Northern Mariana Islands": "mp",
    "Norway": "no",

    "Oman": "om",
    "Pakistan": "pk",
    "Palau": "pw",
    "Palestinian Territory": "ps",

    "Panama": "pa",
    "Papua New Guinea": "pg",
    "Paraguay": "py",
    "Peru": "pe",
    "Philippines": "ph",
    "Pitcairn": "pn",
    "Poland": "pl",
    "Portugal": "pt",
    "Puerto Rico": "pr",
    "Qatar": "qa",
    "Réunion": "re",
    "Romania": "ro",
    "Russian Federation": "ru",
    "Russia": "ru",
    "Rwanda": "rw",
    "Saint-Barthélemy": "bl",
    "Saint Helena": "sh",
    "Saint Kitts and Nevis": "kn",
    "Saint Lucia": "lc",
    "Saint-Martin (French part)": "mf",

    "Saint Pierre and Miquelon": "pm",
    "Saint Vincent and Grenadines": "vc",
    "Samoa": "ws",
    "San Marino": "sm",
    "Sao Tome and Principe": "st",
    "Saudi Arabia": "sa",
    "Senegal": "sn",
    "Serbia": "rs",
    "Seychelles": "sc",
    "Sierra Leone": "sl",
    "Singapore": "sg",
    "Slovakia": "sk",
    "Slovenia": "si",
    "Solomon Islands": "sb",
    "Somalia": "so",
    "South Africa": "za",
    "South Georgia and the South Sandwich Islands": "gs",
    "South Sudan": "ss",
    "Spain": "es",
    "Sri Lanka": "lk",
    "Sudan": "sd",
    "Suriname": "sr",
    "Svalbard and Jan Mayen Islands": "sj",
    "Swaziland": "sz",
    "Sweden": "se",
    "Switzerland": "ch",
    "Syrian Arab Republic": "sy",
    "Taiwan": "tw",
    "Tajikistan": "tj",
    "Tanzania": "tz",
    "Thailand": "th",
    "Timor-Leste": "tl",
    "Togo": "tg",
    "Tokelau": "tk",
    "Tonga": "to",
    "Trinidad and Tobago": "tt",
    "Tunisia": "tn",
    "Turkey": "tr",
    "Turkmenistan": "tm",
    "Turks and Caicos Islands": "tc",
    "Tuvalu": "tv",
    "Uganda": "ug",
    "Ukraine": "ua",
    "United Arab Emirates": "ae",
    "United Kingdom": "gb",
    "United kingdom": "gb",
    "United States of America": "us",
    "USA": "us",
    "United States Minor Outlying Islands": "um",
    "Uruguay": "uy",
    "Uzbekistan": "uz",
    "Vanuatu": "vu",
    "Venezuela": "ve",
    "Vietnam": "vn",
    "Virgin Islands, US": "vi",
    "Wallis and Futuna Islands": "wf",
    "Western Sahara": "eh",
    "Yemen": "ye",
    "Zambia": "zm",
    "Zimbabwe": "zw"
};

var _countries = [];

config.app.regions.forEach(function(region){
    var code = countries[region.country];
    if (!code) {
        console.log(`${region.country} has no code...`);
    } else {
        region.code = code;
        _countries.push({name: region.country, alt: region.country, code: code});
    }
});

config.app.countries = _countries;

module.exports = config;
